### ISSUE TITLE
pnpm build error

### ISSUE THREAD

**Issue by peterroe** [antfu/antfu.me#20]
I just run: 
```shell
$ git clone https://github.com/antfu/antfu.me
$ pnpm i
$ pnpm build
```
An error has occurred when I build：
```shell
[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module 'file:\D:\VscodeItems\antfu.me\.vite-ssg-temp\main.cjs'
Require stack:
- D:\VscodeItems\antfu.me\node_modules\.pnpm\vite-ssg@0.17.2_6acdbf34162ba7e10d9a1c150af90728\node_modules\vite-ssg\dist\node\cli.mjs    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at build (file:///D:/VscodeItems/antfu.me/node_modules/.pnpm/vite-ssg@0.17.2_6acdbf34162ba7e10d9a1c150af90728/node_modules/vite-ssg/dist/node/cli.mjs:185:77)
    at async Object.handler (file:///D:/VscodeItems/antfu.me/node_modules/.pnpm/vite-ssg@0.17.2_6acdbf34162ba7e10d9a1c150af90728/node_modules/vite-ssg/dist/node/cli.mjs:298:3) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\VscodeItems\\antfu.me\\node_modules\\.pnpm\\vite-ssg@0.17.2_6acdbf34162ba7e10d9a1c150af90728\\node_modules\\vite-ssg\\dist\\node\\cli.mjs'
  ]
}
 ELIFECYCLE  Command failed with exit code 1.
```

My env：
```
node: 16.13.1
OS: win10
```

**Comment by antfu** [comment]
Probably fixed already
